/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JButton;
/**
 *
 * @author MAGNER
 */
public class Cuentas extends javax.swing.JFrame {

    // Variables de clase
    public Principal principal = new Principal(); // Instancia de la clase Principal
    public String usuario = "null"; // Nombre del usuario

    /**
     * Constructor de la clase Cuentas.
     * Inicializa los componentes de la interfaz.
     */
    public Cuentas() {
        initComponents(); // Inicialización de componentes
        setLocationRelativeTo(null); // Establece la posición de la ventana en el centro de la pantalla
    }

    /**
     * Constructor de la clase Cuentas que recibe el nombre de usuario como parámetro.
     * @param usu Nombre de usuario
     */
    public Cuentas(String usu) {
        initComponents(); // Inicialización de componentes
        this.usuario = usu; // Asigna el nombre de usuario
        cargar(); // Carga las cuentas asociadas al usuario
        cargarCuentas(usu); // Carga las cuentas en la interfaz
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarCuenta = new javax.swing.JButton();
        btnCambiarContraseña = new javax.swing.JButton();
        panelCuentas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELECCIONE UNA CUENTA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 250, 40));

        btnAgregarCuenta.setBackground(new java.awt.Color(0, 51, 51));
        btnAgregarCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCuenta.setText("AGREGAR CUENTA");
        btnAgregarCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        btnCambiarContraseña.setBackground(new java.awt.Color(0, 51, 51));
        btnCambiarContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCambiarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarContraseña.setText("CAMBIAR CONTRASEÑA");
        btnCambiarContraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        panelCuentas.setBackground(new java.awt.Color(0, 51, 51));
        panelCuentas.setForeground(new java.awt.Color(255, 255, 255));
        panelCuentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelCuentasLayout = new javax.swing.GroupLayout(panelCuentas);
        panelCuentas.setLayout(panelCuentasLayout);
        panelCuentasLayout.setHorizontalGroup(
            panelCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        panelCuentasLayout.setVerticalGroup(
            panelCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(panelCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 560, 210));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngwing.com (4).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, -1, 410));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que carga las cuentas asociadas a un usuario en la interfaz.
     * @param usu Nombre de usuario
     */
    public void cargarCuentas(String usu) {
        if (!principal.getListaCuenta().isEmpty()) { // Verifica si la lista de cuentas no está vacía
            panelCuentas.setLayout(new GridLayout(0, 1)); // Establece el diseño de la lista de cuentas
            
            // Itera sobre la lista de cuentas
            for (int i = 0; i < principal.getListaCuenta().size(); i++) {
                // Verifica si la cuenta pertenece al usuario actual
                if (principal.getListaCuenta().get(i).getUsuario().equals(usu)) {
                    // Crea un botón para la cuenta
                    JButton button = new JButton(String.valueOf(principal.getListaCuenta().get(i).getNumeroCuenta()) + " " + principal.getListaCuenta().get(i).getMoneda());
                    int numeroCuentaAux = principal.getListaCuenta().get(i).getNumeroCuenta();
                    Font fuente = new Font("Arial", Font.BOLD, 18); // Establece la fuente del botón
                    button.setFont(fuente); // Aplica la fuente al botón

                    // Agrega un ActionListener al botón
                    button.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            Menu menu = new Menu(usuario, numeroCuentaAux); // Crea una instancia de la clase Menu
                            menu.setVisible(true); // Hace visible la ventana de menú
                            menu.setLocationRelativeTo(null); // Establece la posición de la ventana en el centro de la pantalla
                            dispose(); // Cierra la ventana actual
                        }
                    });
                    button.setPreferredSize(new Dimension(309, 39)); // Establece el tamaño preferido del botón

                    panelCuentas.add(button); // Agrega el botón al panel de cuentas
                }
            }
        }
    }

    /**
     * Método que carga las cuentas desde un archivo.
     */
    private void cargar() {
        FileInputStream archivo = null; // Variable para leer datos de un archivo
        ObjectInputStream convertidorarchivo = null; // Variable que permite sacar datos del archivo

        try {
            archivo = new FileInputStream("C://Metodos//Cajero.txt"); // Lee el archivo de cuentas
            convertidorarchivo = new ObjectInputStream(archivo); // Convierte el archivo a objetos
            principal = (Principal) convertidorarchivo.readObject(); // Asigna las cuentas al objeto principal
        } catch (IOException ex) { // Manejo de excepciones en caso de error de lectura
            File archivos = new File("C://Metodos//Cajero.txt"); // Crea un nuevo archivo si no existe
        } catch (ClassNotFoundException cnfe) { // Manejo de excepciones en caso de no encontrar la clase
            cnfe.printStackTrace(); // Imprime la traza de la excepción
        }
    }

    /**
     * Método que actualiza la lista de cuentas en el archivo.
     */
    private void actualizarLista() {
        try {
            FileOutputStream ficherosalida = new FileOutputStream("C://Metodos//Cajero.txt"); // Abre el archivo de salida para escribir
            ObjectOutputStream convertidor = new ObjectOutputStream(ficherosalida); // Convierte objetos a bytes
            convertidor.writeObject(principal); // Escribe el objeto principal en el archivo
            convertidor.close(); // Cierra el convertidor
            ficherosalida.close(); // Cierra el archivo de salida
        } catch (IOException ex) { // Manejo de excepciones en caso de error de escritura
            ex.printStackTrace(); // Imprime la traza de la excepción
        }
    }

    /**
     * Método que se ejecuta al hacer clic en el botón "Agregar Cuenta".
     * Abre la ventana para crear una nueva cuenta.
     */
    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        CrearCuenta cuenta = new CrearCuenta(usuario); // Crea una instancia de la clase CrearCuenta
        cuenta.setVisible(true); // Hace visible la ventana para crear una nueva cuenta
        cuenta.setLocationRelativeTo(null); // Establece la posición de la ventana en el centro de la pantalla
        dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_btnAgregarCuentaActionPerformed
    /**
     * Método que se ejecuta al hacer clic en el botón "Cambiar Contraseña".
     * Abre la ventana para cambiar la contraseña.
     */
    private void btnCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraseñaActionPerformed
        CambioContrasena ventana = new CambioContrasena(usuario); // Crea una instancia de la clase CambioContrasena
        ventana.setVisible(true); // Hace visible la ventana para cambiar la contraseña
        ventana.setLocationRelativeTo(null); // Establece la posición de la ventana en el centro de la pantalla
        dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_btnCambiarContraseñaActionPerformed
    /**
     * Método que se ejecuta al hacer clic en el botón "Regresar".
     * Abre la ventana de ingreso de PIN.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IngresoPin ventana = new IngresoPin(usuario); // Crea una instancia de la clase IngresoPin
        ventana.setVisible(true); // Hace visible la ventana de ingreso de PIN
        ventana.setLocationRelativeTo(null); // Establece la posición de la ventana en el centro de la pantalla
        dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Método que se ejecuta al hacer clic en el botón "X" para cerrar la ventana.
     */
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnCambiarContraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCuentas;
    // End of variables declaration//GEN-END:variables
}
